spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
logging:
  pattern:
    console: "%d     %msg%n"
server:
  servlet:
    context-path: /sell


